<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVAWN5dL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVAWN5dL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVAWN5dL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVAWN5dL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVAWN5dL\App_KernelDevDebugContainer([
    'container.build_hash' => 'VAWN5dL',
    'container.build_id' => 'c11e266e',
    'container.build_time' => 1641512581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVAWN5dL');
