version: '3'

services:

  php:
    container_name: bank_php
    environment:
      APP_ENV: dev
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./symfony/:/var/www/symfony/
    depends_on:
      - database
    networks:
      - bank

  nginx:
    container_name: bank_nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - "8001:80"
    networks:
      - bank

  database:
      container_name: bank_database
      image: postgres:13-alpine
      environment:
        POSTGRES_USER: main
        POSTGRES_PASSWORD: main
        POSTGRES_DB: main
      ports:
        - "5432:5432"
networks:
  bank:

