version: "3.9"
   
services:

    bank_db:
        image: postgres
        container_name: bank_db
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
        networks:
            - djangonetwork

    bank_web:
        container_name: bank_web
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        env_file:
            - db.env
        ports:
            - "8000:8000"
        depends_on:
            - bank_db
        networks:
            - djangonetwork

    bank_pgadmin:
        container_name: bank_pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
          - "5555:80"
        depends_on:
          - bank_db
        links:
          - bank_db
        environment:
          PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
          PGADMIN_DEFAULT_PASSWORD: root
networks:
    djangonetwork:
        driver: bridge
